name: EPG Service

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *" # every day at 3:30am UTC (9:00am IST)
  push:
    branches: [ main ]

jobs:

  epg:
    name: EPG Setup
    runs-on: ubuntu-latest
    steps:

    - name: Download binary
      run: |
        curl -L $(curl -s https://1:${{ secrets.RELEASE_TOKEN }}@api.github.com/repos/iMro0t/epg/releases/latest | grep 'browser_' | grep 'epg_' | cut -d\" -f4 | sed 's/github.com/1:'${{ secrets.RELEASE_TOKEN }}'@github.com/g')

    - name: Get EPG Data
      run: ./epg_linux_amd64 -source jiotv
    
    - name: Update release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        hub release edit -a epg.xml -a epg.xml.gz -m "" latest
        

